CREATE TABLE Clients (
	ClientId INT IDENTITY PRIMARY KEY,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	Phone NVARCHAR(12) CHECK(LEN(Phone) = 12) NOT NULL
)

CREATE TABLE Mechanics (
	MechanicId INT IDENTITY PRIMARY KEY,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	Address NVARCHAR(255) NOT NULL
)

CREATE TABLE Models (
	ModelId INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(50) UNIQUE NOT NULL
)

CREATE TABLE Jobs (
	JobId INT IDENTITY PRIMARY KEY,
	ModelId INT FOREIGN KEY REFERENCES Models(ModelId) NOT NULL,
	Status NVARCHAR(11) 
		CHECK(Status IN ('Pending', 'In Progress', 'Finished'))
		DEFAULT('Pending') NOT NULL,
	ClientId INT FOREIGN KEY REFERENCES Clients(ClientId) NOT NULL,
	MechanicId INT FOREIGN KEY REFERENCES Mechanics(MechanicId),
	IssueDate DATETIME NOT NULL,
	FinishDate DATETIME
)

CREATE TABLE Orders (
	OrderId INT IDENTITY PRIMARY KEY,
	JobId INT FOREIGN KEY REFERENCES Jobs(JobId) NOT NULL,
	IssueDate DATETIME,
	Delivered BIT DEFAULT 0 NOT NULL
)

CREATE TABLE Vendors (
	VendorId INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(50) UNIQUE NOT NULL
)

CREATE TABLE Parts (
	PartId INT IDENTITY PRIMARY KEY,
	SerialNumber NVARCHAR(50) UNIQUE NOT NULL,
	Description NVARCHAR(255),
	Price MONEY CHECK(Price <= 9999.99 AND Price > 0) NOT NULL,
	VendorId INT FOREIGN KEY REFERENCES Vendors(VendorId) NOT NULL,
	StockQty INT CHECK(StockQty >= 0) DEFAULT 0 NOT NULL
)

CREATE TABLE OrderParts (
	OrderId INT FOREIGN KEY REFERENCES Orders(OrderId) NOT NULL,
	PartId INT FOREIGN KEY REFERENCES Parts(PartId) NOT NULL,
	Quantity INT CHECK(Quantity > 0) DEFAULT 1 NOT NULL
	CONSTRAINT PK_OrderParts PRIMARY KEY(OrderId, PartId)
)

CREATE TABLE PartsNeeded (
	JobId INT FOREIGN KEY REFERENCES Jobs(JobId) NOT NULL,
	PartId INT FOREIGN KEY REFERENCES Parts(PartId) NOT NULL,
	Quantity INT CHECK(Quantity > 0) DEFAULT 1 NOT NULL
	CONSTRAINT PK_PartsNeeded PRIMARY KEY(JobId, PartId)
)