CREATE TABLE Clients (
    Id INT PRIMARY KEY IDENTITY,
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL
)

CREATE TABLE AccountTypes (
    Id INT PRIMARY KEY IDENTITY,
    [Name] NVARCHAR(50) NOT NULL
)
 
CREATE TABLE Accounts(
    Id INT PRIMARY KEY IDENTITY NOT NULL,
    ClientId INT FOREIGN KEY REFERENCES Clients(Id),
    AccountTypeId INT FOREIGN KEY REFERENCES AccountTypes(Id),
    Balance DECIMAL(15, 2) DEFAULT 0
)